{"name": "test_delete_product_with_invalid_id", "status": "failed", "statusDetails": {"message": "Failed: DID NOT RAISE <class 'Exception'>", "trace": "products_table = <dbs.sqlite_products_table.SqliteProductsTable object at 0x106de8620>\n\n    def test_delete_product_with_invalid_id(products_table):\n        # Negative test: Attempt to delete a product with an invalid ID\n    \n        # Invalid product ID (non-existent)\n        invalid_product_id = -1\n    \n        # Attempt to delete the product with the invalid ID\n>       with pytest.raises(Exception) as exc_info:\nE       Failed: DID NOT RAISE <class 'Exception'>\n\ntest_get_products.py:60: Failed"}, "start": 1712611301081, "stop": 1712611301085, "uuid": "f1e18761-b86f-455c-a7f3-7c55b9126ad2", "historyId": "0e2b0779f7c39af8dad96a4fbc340434", "testCaseId": "0e2b0779f7c39af8dad96a4fbc340434", "fullName": "test.db_tests.test_get_products#test_delete_product_with_invalid_id", "labels": [{"name": "parentSuite", "value": "test.db_tests"}, {"name": "suite", "value": "test_get_products"}, {"name": "host", "value": "dariias-mbp.home"}, {"name": "thread", "value": "14969-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.db_tests.test_get_products"}]}